name: Scout tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7]
        mongodb-version: ["3.6", "4.0"]

    steps:
    
    # Chgeck out Scout code
    - uses: actions/checkout@v1
    
    # Set up python
    - name: Set up Python ${{ matrix.python-version}}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version}}
    
    # Set up mongodb
    - name: Start MongoDB
      uses: wbari/start-mongoDB@v0.2
      with:
        mongoDBVersion: ${{ matrix.mongodb-version}}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cython
        pip install -r requirements-dev.txt -e .
  
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pip install pytest
        py.test --cov=scout -rxs tests/
    
    - name: Package Install
      run: |
        pip check
    
